package com.example.primipreguntas;

public  class Constants {
    public static Pregunta facil[] = {
            new Pregunta("¿Cuál es la carga académica mínima de un estudiante?","10 créditos"),
            new Pregunta("¿Cuál es el número máximo de matrículas que puede tener un estudiante?","20 matrículas"),
            new Pregunta("¿Cuál es el número del edificio Insignia Julio Garavito Armero?","401"),
            new Pregunta("¿Por cuál periodo de tiempo se calcula el PAPI?","Semestre inmediatamente culminado"),
            new Pregunta("¿Cuál es el uso del P.A.P.I?","Inscripción de materias del semestre siguiente"),
            new Pregunta("¿Son el P.A.P.I, el P.A.P.A y el P.A iguales?","No"),
            new Pregunta("¿Cuáles son 3 diferentes promedios en la UN?","P.A.P.A, P.A.P.I y P.A."),
            new Pregunta("¿En cuales semanas del semestre se pueden cancelar materias sin pérdida de créditos?","Semanas 1 y 2"),
            new Pregunta("¿Cuántas veces se puede solicitar reingreso?", "Una vez"),
            new Pregunta("¿Cuál es la nota numérica mínima para aprobar una materia?","3.0"),
            new Pregunta("¿Qué significa las siglas P.A?","Promedio académico"),
            new Pregunta("¿Cuál es el número del edificio de ciencia y tecnología Luis Carlos Sarmiento Angulo?","454"),
            new Pregunta("¿Hasta cuándo puedo realizar cancelación de asignaturas libremente y sin requisitos?", "Antes de completarse el 50% del período académico ((8tava semana)"),
            new Pregunta("¿Si cancelo entre la semana 3 y la 8, tengo pérdida de créditos , afecta mi P.A.P.P.I.?","SI y me temo que SI"),
            new Pregunta("¿Cuál es el P.A.P.A. mínimo con el que puedo solicitar reingreso cunado pierdo la calidad por falta de créditos para terminar la carrera?","2/07/2019"),
            new Pregunta("Nombre dos de las posibles razones por la cual un estudiante de pregrado puede perder la calidad de estudiante ","1. Culminar exitosamente los planes de estudio en los que fue aceptado. \n2. No cumplir con los requisitos exigidos para la renovación de la matrícula, en los plazos señalados por la Universidad. \n3. Presentar un Promedio Aritmético Ponderado Acumulado menor que tres punto cero (3.0).\n4. No disponer de un cupo de créditos suficiente para inscribir las asignaturas del plan de estudios pendientes de aprobación.\n5. Recibir sanción disciplinaria de expulsión o suspensión impuesta de acuerdo con las normas vigentes."),
            new Pregunta("Cuando la asistencia mínima exigida en una asignatura no se cumpla, ¿Qué calificación se otorgará a esta asignatura?","0.0"),
            new Pregunta("Al terminar el plan de estudio al que fue aceptado, ¿se pierde la calidad de estudiante? ","Si"),
            new Pregunta("¿Cómo se adquiere la calidad de estudiante en la Universidad Nacional de Colombia? ","Haciendo uso de la matrícula inicial"),
            new Pregunta("¿Puedo recibir tres apoyos socioeconómicos? ","No. Sólo dos"),
            new Pregunta("¿Cuál es la condición para pedir un reingreso y quién lo autoriza? ","Tener un PAPA mayor o igual a 2.7. Lo autoriza el Consejo de Facultad "),
            new Pregunta("¿Es posible la doble titulación en convenio con otras instituciones?", "Si"),
            new Pregunta("cuál es la razón por la cual se puede obtener una beca para posgrados", "Quien obtenga la distinción \"Grado de Honor de pregrado\""),
            new Pregunta("¿Puede un estudiante presentar un supletorio debido a que el día del examen se cruza con una actividad deportiva en la que representa a la universidad?", "Si, presentando su debido soporte o permiso académico"),
            new Pregunta("¿Cuáles son los tipos de evaluaciones?", "Ordinarias, supletorias y de validación"),
            new Pregunta("¿Durante que periodo se pueden cancelar asignaturas libremente sin pérdida de créditos?", "Durante las dos primeras semanas de clases"),
            new Pregunta("¿Durante que periodo se pueden cancelar asignaturas libremente con pérdida de créditos?", "Entre la tercera y la octava semana de clases "),
            new Pregunta("¿En qué piso están ubicadas las salas de estudio del edifico 401?","3er Piso"),
            new Pregunta("¿En qué edificio están ubicadas las oficinas de los departamentos de Ingenieria?","453"),
            new Pregunta("¿Dónde queda una de las oficinas de Bienestar?","1er Piso y 3er Piso del 401"),
            new Pregunta("El edificio insignia de la Facultad de Ingeniería Julio Garavito Armero, lleva el nombre de un", "Ingeniero"),
            new Pregunta("El edificio de matemáticas Yu-Takeuchi lleva el nombre de un", "Docente de la Universidad Nacional"),
            new Pregunta("¿Cuál es el número del edificio \"Laboratorios de ingeniería\"?","411"),
            new Pregunta("Nombre los tres tipos de evaluaciones académicas para las asignaturas.","* Ordinarias\n*Supletorias\n* De validación"),
            new Pregunta("¿Si se aprueba la cancelación de periodo académico, el alumno pierde calidad de estudiante? ","No, el estudiante mantendrá la calidad de estudiante durante ese periodo académico."),
            new Pregunta("¿Cómo se obtiene el cupo adicional de créditos?", "Por cada crédito aprobado se adicionan dos al cupo adicional de créditos, hasta un tope de 80."),
            new Pregunta("¿Cuál es el nombre de la biblioteca central de la Universidad Nacional de Colombia?", "Biblioteca central Gabriel García Márquez"),
            new Pregunta("¿Qué significa I.E.I.?","Instituto de Extensión e Investigación"),
            new Pregunta("¿Cómo se llama la actual directora de Bienestar universitario de la Facultad de Ingeniería de la Sede Bogotá?", "Gloria Inés Beltrán Calvo"),
            new Pregunta("¿Qué es lo único que se debe hacer para estar en reserva de cupo?", "No realizar el pago de la matrícula para el semestre que se desea \"reservar\" y no inscribir ninguna materia"),
            new Pregunta("Cuántos auditorios tiene el CyT?","1"),
            new Pregunta("A partir de que semestre el estudiante hace la inscripción de asignaturas por su cuenta?", "Segundo"),
            new Pregunta("¿A través de que aplicativo se inscriben materias?","SIA "),
            new Pregunta("¿A qué personaje hace honor el nombre de la Biblioteca Central?", "Gabriel García Márquez"),
            new Pregunta("¿Por qué es importante tener un buen P.A.P.P.I?","Por qué nos permitirá inscribir las materias con los mejores horarios y profesores "),
            new Pregunta("¿En cuál plataforma se solicitan los apoyos socioeconómicos?","SIBU"),
            new Pregunta("¿Con qué promedio se pierde la calidad de estudiante?","3.0 "),
            new Pregunta("¿Qué pasa si no se renueva la matrícula el siguiente semestre?", "Automáticamente el estudiante entra en reserva de cupo"),
            new Pregunta("¿Cuál es el verdadero nombre de la plaza che?", "Plaza Francisco de Paula Santander"),
            new Pregunta("¿El estudiante tiene un límite máximo de créditos a cursar semestralmente?", "No"),
            new Pregunta("¿De qué año a que año transcurrirá la actual rectoría de la sede Bogotá?","2018-2021"),
            new Pregunta("¿Qué día finalizan las clases del segundo periodo Académico 2019-II? ","Diciembre 13 del 2019"),
            new Pregunta("¿Qué día finaliza la adición y cancelación de asignaturas sin pérdidas de créditos?", "septiembre 06 del 2019"),
            new Pregunta("¿Cuáles son las asignaturas de nivelación?", "Matemáticas básicas, lecto-escritura e inglés "),
            new Pregunta("¿Como se llama la oficina donde se solicita y se reclama el carnet estudiantil? ","Oficina de registro y matrícula"),
            new Pregunta("¿Nombre mínimo tres sedes de la Universidad Nacional de Colombia?", "Sedes: Bogotá, Medellín, Manizales, Palmira, Amazonía, Caribe Valledupar, Caribe San Andrés, Orinoquía, Pacífico"),
            new Pregunta("¿Nombre al menos dos entradas principales a la Universidad Nacional de Colombia sede Bogotá? ","Entradas principales: Calle 45 con Cra. 30, Calle 26 con Cra. 39, Calle 53 con Cra. 39 y Uriel Gutiérrez ."),
            new Pregunta("¿Cuántos son los apoyos socioeconómicos brindados por la universidad?","4"),
            new Pregunta("¿Cuál es el número del edificio del instituto de genética?","426"),
            new Pregunta("¿Como se llama el actual rector(a) de la universidad?", "Dolly Montoya Castaño"),
            new Pregunta("¿Cuál es el documento de identificación de la comunidad universitaria?", "Carné estudiantil TIUN"),
            new Pregunta("¿Cuál es el nombre del sistema de bibliotecas de la Universidad?","SINAB"),
            new Pregunta("¿Se puede ingresar en bicicleta propia al campus universitario?", "Si, la bicicleta debe ser registrada en el punto BICIRUN de la calle 26"),
            new Pregunta("¿Puedo hacer doble titulación en Posgrado?", "No"),
            new Pregunta("¿Cuántas matrículas debo pagar por semestre en caso tal que esté haciendo doble titulación?.","1"),
            new Pregunta("¿Puedo pedir doble titulación en un plan de estudios en el cual haya tenido la calidad de estudiante?", "No"),
            new Pregunta("¿Cuál es el número máximo de semestres que puedo acceder a apoyos socioeconómicos?", "Dos semestres adicionales a los semestres estipulados para terminar el programa curricular."),
            new Pregunta("¿En qué casos se pueden condonar las horas de corresponsabilidad?", "Ser coordinador de proyecto estudiantil o pertenecer a una selección deportiva "),
            new Pregunta("Si se tienen dos apoyos socioeconómicos, ¿Cuántas horas debo hacer de corresponsabilidad?", "Las horas del apoyo que más número de horas requiera. "),
    };
    public static Pregunta medio[] = {
            new Pregunta("¿Nombre una distinción que puede recibir un estudiante cuando se gradúa?", "Grado de Honor, Admisión automática."),
            new Pregunta("¿ Nombre un estímulo que puede recibir un estudiante cuando se gradúa?","Mejores trabajos de grado en pregrado, Becas de posgrado."),
            new Pregunta("¿ Durante la reserva de cupo se tiene calidad de estudiante?", "No."),
            new Pregunta("¿Por cuál factor (nota) se multiplica a una materia cancelada entre la semana 3 y 8 para el cálculo del P.A.P.I?","Se multiplica por una nota o factor de 0,0"),
            new Pregunta("¿Qué es lo que significa la sigla P.A.P.A, en el contexto académico de la Universidad Nacional de Colombia?", "Promedio Aritmético Ponderado Acumulado"),
            new Pregunta("¿A cuál promedio (P.A.P.A; P.A; y P.A.P.I), afecta la cancelación de una asignatura en la semana 1 y 2?","A ninguno"),
            new Pregunta("¿Con que P.AP.A se pierde la calidad de estudiante?", "Inferior a 3.0"),
            new Pregunta("¿Cómo se define el orden de inscripción de materias para los semestres posteriores al primero?", "De mayor a menor PAPI"),
            new Pregunta("¿Cuál es el cupo adicional de créditos?","80 créditos"),
            new Pregunta("Describa dos formas en las cuales se puede perder la calidad de estudiante","■ Culminar exitosamente los planes de estudio en los que fue aceptado.\n■ No cumplir con los requisitos exigidos para la renovación de la matrícula, en los plazos señalados por la Universidad.\n■ Presentar un Promedio Aritmético Ponderado Acumulado menor que tres punto cero (3.0).\n■ No disponer de un cupo de créditos suficiente para inscribir las asignaturas del plan de estudios pendientes de aprobación.\n■ Recibir sanción disciplinaria de expulsión o suspensión impuesta de acuerdo con las normas vigentes."),
            new Pregunta("¿Qué es una evaluación ordinaria?", "Es la que se realiza en el transcurso de cada período académico y se establece en el programa-calendario."),
            new Pregunta("¿Cuáles son las calificaciones alfabéticas?","AP, NA y NP"),
            new Pregunta("¿Cuál es el ente que puede aprobar una cancelación extemporánea sin pérdida de créditos ?","caso fortuito debidamente documentado o por traslado entre programas de la Universidad, el Consejo de Facultad podrá autorizar la cancelación del período académico, es decir de la totalidad de asignaturas o actividades académicas inscritas."),
            new Pregunta("Nombre al menos 3 de sus deberes como estudiante ","■ Conocer y acoger los programas, evaluaciones y planes de estudio que sean definidos por la Universidad.\n■ Actuar con honestidad en la elaboración y presentación de pruebas de evaluación académica .\n■ Respetar y acatar, en especial las normas relacionadas con propiedad intelectual .\n■ Cuidar y preservar el patrimonio cultural, histórico, artístico, arquitectónico, urbanístico y ecológico de la universidad. .\n■ Exigir una formación académica de calidad y contribuir con la excelencia académica. .\n■ Respetar las opiniones y los puntos de vista de los demás y permitir su libre expresión. .\n■ Participar en los procesos de evaluación docente y de autoevaluación institucional, de conformidad con los estatutos y mecanismos establecidos para tal efecto.\n■ Participar en la elección de la representación estudiantil, para los cuerpos colegiados en los que su participación esté establecida."),
            new Pregunta("Nombre al menos 2 Apoyos socioeconómicos estudiantiles.","■ Apoyo para el alojamiento estudiantil.\n■ Apoyo alimentario estudiantil. \n■ Apoyo para el transporte estudiantil."),
            new Pregunta("Cuál es el cupo máximo de créditos que se le pueden otorgar a un estudiante que solicita reingreso, por causa de pérdida de calidad de estudiante de no disponer de un cupo suficiente de créditos para la inscripción?","10 Créditos máximo"),
            new Pregunta("Si no logra un acuerdo con su profesor sobre una nota de evolución ordinaria, cuantos días hábiles máximos tiene para hacer una reclamacion?","5 días hábiles máximo"),
            new Pregunta("Si no logra un acuerdo con su profesor sobre una nota de evolución ordinaria, ¿ante quien se debe realizar el reclamo correspondiente? ","Ante el director de la Unidad Académica Básica que ofrece la asignatura"),
            new Pregunta("¿Cómo se llama el acuerdo por el cual se adopta el Estatuto Estudiantil de la Universidad Nacional de Colombia? ","Acuerdo 008 del 2008"),
            new Pregunta("¿Qué requisitos son necesarios para realizar un traslado de carrera? ","Haber cursado un semestre en el programa admitido y tener derecho a renovación de matrícula "),
            new Pregunta("¿Por qué puedo perder la calidad de estudiante antes de iniciar el primer semestre? ","Por no hacer uso del derecho a la matrícula inicial "),
            new Pregunta("Nombre al menos 2 de las 11 solicitudes que se pueden realizar a través del el portal SIA","Autorización para Cursar Menos de la Carga Mínima * Cancelación de Asignaturas Posterior a la mitad del Período Académico * Cancelación de Periodo Académico * Doble Titulación * Homologación y Convalidación de Asignaturas * Inscripción para Grado * Registro Trabajo de grado * Reingreso * Reserva de Cupo Adicional * Traslado de Programa Curricular"),
            new Pregunta("Nombre al menos 2 de las 8 características que debe tener el programa de una asignatura", "Identificación de la asignatura: nombre completo, código y número de créditos * Metodología a utilizar * Distribución de los temas y subtemas del programa-asignatura. * Carácter, tipo y ponderación de pruebas. * Fechas de presentación de pruebas. * Porcentaje mínimo exigido de asistencia, de acuerdo con el programa-asignatura * Bibliografía. * Si la asignatura es validable o no."),
            new Pregunta("Diga la diferencia entre permiso académico y excusa", "La diferencia es que el permiso académico se entrega con antelación a la falla y la excusa se presenta después de haber fallado a la clase"),
            new Pregunta("Nombre dos razones por las que un estudiante puede perder la calidad de estudiante","1. Culminar exitosamente el plan de estudios \n2. Promedio menor a 3.0 \n3. No disponer de los créditos suficientes "),
            new Pregunta("¿En qué consiste la reserva de cupo?", "La reserva de cupo es la suspensión temporal de los estudios por un periodo académico"),
            new Pregunta("¿Cuantas veces un estudiante puede realizar la reserva de cupo?","2 veces"),
            new Pregunta("Juan acaba de enterarse que perdió su primer parcial con 0.1 en la semana 5 del semestre, ¿Que debe hacer Juan si quiere cancelar la materia?", "Revisar su horario de cancelación ya que aún no ha pasado la 8 semana, aunque se atendrá a la perdida de créditos de esa materia"),
            new Pregunta("Andrés está preocupado por que debido a una situación familiar de fuerza mayor debe viajar a su lugar de origen, ya que perdería dinero y los créditos del semestre, ¿Cuál sería tu recomendación a Andrés? ","Que si el motivo de la cancelación es aprobado, se le devolverá un porcentaje de la matrícula y sus créditos serán reintegrados, es decir, no se debe preocupar por la cancelación si está bien justificada"),
            new Pregunta("Alejandra le ha dado pereza ir a más de la mitad de las clases de Matemáticas Básicas ¿Cual podría ser la nota final de Alejandra en Matemáticas Basicas?","0.0 por fallas"),
            new Pregunta("Nombre del director del departamento de Ingeniería Mecánica y Mecatrónica", "Aldo Germán Benavidez"),
            new Pregunta("¿ Cuántos programas de ingeniería pertenecen a la Facultad de Ingeniería de la sede Bogotá? ","9"),
            new Pregunta("¿ Cuántas razones o causas existen para perder la calidad de estudiante de pregrado de la Universidad Nacional De Colombia?","5"),
            new Pregunta("¿Qué es el cupo adicional de créditos?", "El cupo adicional de créditos es la mitad del mínimo de los créditos que contempla el plan de estudios para el que fue admitido y puede llegar a un máximo de ochenta (80) créditos."),
            new Pregunta("Mencione tres requisitos para realizar traslado de carrera:","* No haber perdido la calidad de estudiante en la carrera de destino.\n* Haber cursado como mínimo un periodo académico dentro de la universidad.\n* El traslado está condicionado a conservar la calidad de estudiante en el periodo académico siguiente.\n* Que el estudiante cuente con el suficiente cupo de créditos para la culminación del nuevo plan de estudios."),
            new Pregunta("¿Cuantas reservas de cupo puede tener un estudiante de pregrado?", "Dos , aunque en caso de tener una situación debidamente justificada el consejo de Facultad podrá aprobar otras."),
            new Pregunta("¿Qué significa \"NA\" en la historia académica y qué debe hacer con esa asignatura? ","Significa \"No Aprobado\" y debe repetir esa materia"),
            new Pregunta("¿Qué beneficio recibe un estudiante que se encuentre en la lista de los mejores promedios de su carrera?", "Descuento en el recibo de pago por concepto de matrícula"),
            new Pregunta("¿Cuál es el máximo valor económico que puede recibir un estudiante de preparado referente a apoyos económicos?", "Un SMLV equivalente a 820000"),
            new Pregunta("Que debe hacer el estudiante si quiere ver menos de 10 créditos que son los mínimos para cursar un semestre?", "Tendrá que realizar una solicitud justificada ante consejo de facultad los cuales aprobarán o no dicha petición."),
            new Pregunta("Cuantas aulas tiene el CyT?","20"),
            new Pregunta("Entre que años se remodelo el edificio insignia de ingenieria?","2011-2014"),
            new Pregunta("¿Cuál es el otro pregrado qué hace parte de su departamento?", "Civil- Agrícola. Electrica-Electronica. Industrial - Sistemas.  Mecánica- Mecatrónica. Química no tiene"),
            new Pregunta("Si se desea cancelar un semestre, ¿se debe enviar una carta dirigida al Consejo de Facultad, al Consejo de Sede o al Consejo Superior Universitario?", "Al Consejo de Facultad"),
            new Pregunta("¿Cuál es el P.A.P.A mínimo requerido para solicitar un reingreso?","2/07/2019"),
            new Pregunta("¿Cuántos pregrados en ingeniería hay en la Facultad de Ingeniería?","9"),
            new Pregunta("¿A dónde se debe llevar la solicitud para homologar materias?", "CASE"),
            new Pregunta("¿Cuál es el cupo máximo adicional de créditos que puede tener un estudiante?", "La mitad de los créditos que contiene el plan de estudios y un máximo de 80 "),
            new Pregunta("¿En qué año se fundó la Universidad Nacional de Colombia?","1867"),
            new Pregunta("¿Como se llama la página de recursos bibliográficos de la U Nacional?","SINAB"),
            new Pregunta("¿Cuál fue la primera ingeniería de la universidad Nacional?", "Ingeniería civil"),
            new Pregunta("¿Qué es y para qué sirve el cupo de créditos en pregrado?", "Cada estudiante tendrá un cupo de créditos para inscripción de asignaturas. Este cupo corresponde a los créditos que contempla el plan de estudios a la que fue admitida la estudiante."),
            new Pregunta("¿Qué son los créditos inscritos? ","Corresponden a la suma de los créditos de las asignaturas inscritas por las estudiantes en cada periodo académico. "),
            new Pregunta("¿Qué son los créditos aprobados?", "Es la suma de los créditos inscritos de asignaturas calificadas con nota aprobatoria."),
            new Pregunta("¿Como se llama el programa de préstamo de bicicletas de la comunidad universitaria? ","BicirrUN"),
            new Pregunta(" ¿Qué son los créditos del plan de estudios requeridos?", "Es la cantidad mínima de créditos que debe aprobar una estudiante para culminar su plan de estudios."),
            new Pregunta("¿Cuántos años cumple la Universidad Nacional de Colombia?", "La Universidad Nacional de Colombia cumple 152 años"),
            new Pregunta("¿Como acceder a los apoyos socioeconómicos?", "Ser estudiante activo de la universidad, inscribirse en la respectiva convocatoria, diligenciar la documentación correspondiente, no recibir más de un apoyo económico por parte de otras dependencias de la universidad"),
            new Pregunta("Si ocurre una emergencia médica dentro del campus ¿A qué lugar se debe recurrir? ","Instituto de genética "),
            new Pregunta("¿Dónde se encuentra la rectoría de la universidad?", "Unidad Uriel Gutiérrez "),
            new Pregunta("¿Es necesario ir hasta una biblioteca de la UN para renovar un libro?", "No, la renovación puede hacerse a través del SINAB"),
            new Pregunta("¿Se pueden realizar inscripción de asignaturas si se debe una multa en la biblioteca?", "No, para realizar adiciones o cancelaciones es necesario estar a paz y salvo"),
            new Pregunta("Mencione al menos dos bibliotecas del campus ","Biblioteca central Gabriel García Márquez, Biblioteca de Ciencia y Tecnología "),
            new Pregunta("¿Puedo pedir doble titulación en un plan de estudios en el cual haya tenido la calidad de estudiante?", "No"),
            new Pregunta("¿Cuántos es el número de créditos máximo que se le pueden otorgar en caso tal de que la bolsa de créditos no alcance para optar por doble titulación?.","10 créditos"),
            new Pregunta("¿Cuál es el PAPA necesario para recibir en caso de ser necesario un cupo adicional de créditos para inscripción?", "Mayor o igual a 4.3"),
            new Pregunta("Si no pago el recibo, ni inscribo, ¿sigo siendo estudiante de la universidad? ","No"),
            new Pregunta("¿Cuál es el porcentaje máximo de convalidación de materias para un pregrado? ","50"),
            new Pregunta("¿La cancelación libre de asignaturas implica pérdida de créditos?", "No "),
    };
    public static Pregunta dificil[]={
            new Pregunta("¿Diferencia entre Homologación y Convalidación?","La homologación se realiza cuando la asignatura tiene un contenido similar y la convalidación es cuando el contenido es diferente. Puede ser de la misma o de diferente universidad."),
            new Pregunta("¿Diferencia entre Homologación y equivalencia?","La homologación se realiza cuando la asignatura tiene un contenido similar y es de otra IES y la equivalencia es cuando el contenido es similar pero de la UN"),
            new Pregunta("¿Diferencia entre convalidación y equivalencia?","Una convalidación se realiza cuando el contenido es distinto y es cursada en la UN o en otra IES mientras que la equivalencia es para contenido similar pero cursada en la UN"),
            new Pregunta("¿Cuál es la diferencia entre P.A. y P.A. P.A?","El Promedio Aritmético es el promedio calculado que sirve para cualquier evento externo de la universidad, no incluye las materias perdidas mientras que el P.A.P.A, promedio aritmético ponderado acumulado, por tanto incluye todas las materias del historial del estudiante y se utiliza para todos los trámites , procesos y convocatorias internos de la universidad."),
            new Pregunta("¿Cómo se calcula el P.A.P.A?","Se calcula multiplicando la nota obtenida de la asignatura por el número de créditos de la asignatura se suman estos resultados de todas las materias inscritas y este resultado se divide entre la suma del número de créditos cursados."),
            new Pregunta("¿En qué semestre es seguro que el P.A y el P.A.P.A, son númericamente iguales?", "En el primer semestre."),
            new Pregunta("¿Cómo se hace la reserva de cupo?", "No haciendo uso de la renovación de la matrícula. "),
            new Pregunta("¿Cuáles son los requisitos necesarios para solicitar la doble titulación?", "Tener un promedio mayor a 4,3 o tener créditos disponibles en la bolsa adicional de créditos."),
            new Pregunta("¿Cuál es el número del acuerdo y el año donde se encuentra el estatuto estudiantil?","Acuerdo 008 de 2008"),
            new Pregunta("¿De cuánto tiempo dispone el docente para dar a conocer las calificaciones de las evaluaciones ordinarias?","10 días hábiles siguientes a su realización"),
            new Pregunta("Nombre dos apoyos socioeconómicos de sede.", "Gestión, económica, gestión alimentaria, gestión para alojamiento o gestión para el transporte"),
            new Pregunta("Nombre dos apoyos socioeconómicos de Facultad.", "Estudiantes auxiliares o promotores de convivencia"),
            new Pregunta("Tiempo máximo de duración de los apoyos socioeconómicos durante el plan de estudios", "Dependiendo de los créditos de la carrera: \n■ Menos 139 créditos hasta 8 periodos. \n■ 140 - 186 hasta 10 periodos. \n■ Mas de 186 hasta 12 periodos"),
            new Pregunta("Cual es la diferencia ente la Vinculación como estudiantes monitores o estudiantes auxiliares", "Monitoria Académica\nEs una distinción que la Universidad puede otorgar a los mejores estudiantes de pregrado y posgrado, para que como parte integral de su proceso de formación, participen en actividades de docencia, investigación y extensión.\nEstudiante Auxiliar\nEs un estímulo para que los estudiantes como complemento a su formación integral apoyen actividades de docencia, investigación, extensión, bienestar universitario y de gestión administrativa de la Universidad Nacional de Colombia."),
            new Pregunta("Nombre 2 Miembros del Comité Asesor Pregrado","°2 Directores Área Curricular.\n°2 Representantes Profesores.\n°2 Representantes Estudiantiles(Principal y suplente). \n°Director Departamento"),
            new Pregunta("¿dentro de cuantos años máximo se puede pedir el reingreso, después de haber perdido la calidad de estudiante?","3 años"),
            new Pregunta("¿un estudiante de pregrado puede perder la calidad de estudiante por superar un tiempo de permanencia máximo?", "NO, solo los estudiantes de posgrado pueden perder calidad de estudiantes por esta causa"),
            new Pregunta("¿Quién otorga el reingreso de un estudiante que puede calidad de estudiante? ","Los Consejos de Facultad"),
            new Pregunta("¿Antes de qué porcentaje del periodo académico puedo cancelar asignaturas sin realizar trámites ante el Consejo de Facultad? ","Antes del 50% del periodo académico"),
            new Pregunta("¿Cuándo se concede el título de \"Grado póstumo\"? ","Cuando un estudiante fallezca y esto se da según criterio del Consejo de Sede"),
            new Pregunta("¿Qué puedo hacer con los créditos que me sobren al finalizar mi carrera? ","Los puedo usar para disminuir el costo de mis materias en Posgrado. "),
            new Pregunta("¿Por qué un estudiante es meritorio de admisión automática?", "Los estudiantes de pregrado de la Universidad Nacional podrán continuar estudios de posgrado sin presentar examen de admisión, cuando al graduarse pertenezcan al grupo del diez por ciento (10%) de los estudiantes con el mejor rendimiento académico de su programa curricular, de acuerdo con la disponibilidad de cupos en el posgrado y según reglamentación del Consejo Académico."),
            new Pregunta("¿Qué requisito debe cumplir un estudiante para recibir exención de pago de matrícula? (nombre al menos 1)","En cada período académico se otorgará exención en el pago de la matrícula a los quince (15) estudiantes de cada programa curricular de pregrado que presenten el mejor rendimiento académico."),
            new Pregunta("Qué principal característica le permite a un docente decidir si hace o no un supletorio", "Libertad de cátedra, excusa médica, permiso académico (cualquiera es correcta)"),
            new Pregunta("Documento que el profesor debe entregar al inicio del semestre con todo lo concerniente a su materia ","El programa-asignatura "),
            new Pregunta("¿Qué pasa si no cumple con la asistencia mínima exigida?", "La asignatura se pierde con 0.0 "),
            new Pregunta("¿Cuál es el promedio mínimo para pedir un reingreso a la universidad?","Un PAPA de 2.7"),
            new Pregunta("¿En qué consiste la revisión de las calificaciones de evaluaciones ordinarias?", "La revisión de las calificaciones de evaluaciones ordinarias podrá ser reclamada, por una sola vez, dentro de los cinco (5) días hábiles siguientes a la entrega de la nota, ante el Director de la Unidad Académica Básica que ofrece la asignatura, quien designará dos (2) nuevos calificadores. La nota definitiva correspondiente a la prueba reclamada será el promedio de las calificaciones otorgadas por los dos nuevos calificadores."),
            new Pregunta("Mencione 3 maneras de perder la calidad de estudiante","1. Culminar exitosamente los planes de estudio en los que fue aceptado.\n2. No cumplir con los requisitos exigidos para la renovación de la matrícula, en los plazos señalados por la Universidad.\n3. Presentar un Promedio Aritmético Ponderado Acumulado menor que tres punto cero (3.0).\n4. No disponer de un cupo de créditos suficiente para inscribir las asignaturas del plan de estudios pendientes de aprobación.\n5. Recibir sanción disciplinaria de expulsión o suspensión impuesta de acuerdo con las normas vigentes."),
            new Pregunta("¿Como obtener la distinción de Grado de Honor en Pregrado?", "Se le otorga a quienes hayan obtenido la exención de pago de matrícula en todos los períodos académicos cursados (con excepción del primero), no hayan reprobado asignatura alguna y no hayan tenido sanciones disciplinarias."),
            new Pregunta("¿En qué año se inauguró la Biblioteca Central Gabriel García Márquez?","1971"),
            new Pregunta("¿Cuál es el número del artículo del estatuto estudiantil que habla acerca de la pérdida de la calidad de estudiante?","44"),
            new Pregunta("¿Con cuántos docentes en total cuenta el Departamento de Ingeniería Mecánica y Mecatrónica?","45"),
            new Pregunta("¿Con que promedio un estudiante de posgrado pierde la calidad de estudiante y puede solicitar reingreso?", "Se pierde la calidad de estudiante en posgrado con un promedio menor a 3.5, en este caso no se cuenta con el derecho a solicitar reingreso."),
            new Pregunta("Que normas debe seguir una prueba de validación:", "a. El estudiante que opte por la validación asumirá la preparación . b. Las evaluaciones de validación se harán y calificarán por un jurado integrado por no menos de dos profesores de la Unidad Académica que ofrece la asignatura. c. Las asignaturas validadas tienen el mismo efecto que las asignaturas cursadas en un período académico. d. Los créditos de las asignaturas validadas en pregrado se descontarán del cupo de créditos para inscripción, independientemente de la calificación obtenida."),
            new Pregunta("Mencione el conducto regular en orden jerárquico de menor a mayor nivel.","* Profesor/Tutor\n* Director de área curricular\n* Comité asesor de carrera\n* Consejo de Facultad.\n* Consejo de Sede.\n* Consejo Superior Universitario."),
            new Pregunta("¿Cuáles son los criterios de evaluación para conceder un traslado de programa curricular interfacultad o intrafacultad?","-Avance mínimo del primer plan de estudios del 30% -Estar en la franja del 10% de los mejores promedios del programa al cual se solicita el traslado -Tener el puntaje del último admitido al programa que se solicita el traslado "),
            new Pregunta("¿Qué significa AS en la historia académica?", "Avance Satisfactorio"),
            new Pregunta("¿Qué significado tiene la palabra crédito referente al contexto de la historia académica?", "Un crédito académico es la unidad que mide el tiempo que, como estudiante de pregrado o posgrado requieres para cumplir a cabalidad los objetivos de formación de cada asignatura o actividad académica.  "),
            new Pregunta("Quien donó el CyT?","Luis Carlos Sarmiento Angulo"),
            new Pregunta("¿Cuándo se inauguró el CyT?","2008"),
            new Pregunta("Mencione los 3 tipos de cancelaciones de asignaturas que ehay", "Sin pérdida de créditos, con pérdida de créditos antes del 50 % del semestre, y con pérdida de créditos posterior al 50% del semestre"),
            new Pregunta("¿A qué edificio debemos ir si nos sentimos enfermos o hay un accidente moderado dentro del campus?", "Al Instituto de Genética, ubicado cerca de la portería de la calle 53"),
            new Pregunta("Nombre al menos 3 de todos los apoyos socioeconómicos a los que se puede acceder en la Universidad", "Apoyo de Transporte, Apoyo Alimentario, Residencia estudiantil, Promotor de Convivencia, Estudiante Auxiliar."),
            new Pregunta("¿Qué es un crédito académico?", "Es una medida que indica la intensidad horaria que se le debe dedicar a una materia"),
            new Pregunta("Si el estudiante tiene menos del 30% de avance en su carrera, con qué criterio lo evalúan para realizar traslado a otra sede?", "El puntaje en la prueba de admisión debe ser mayor al del último admitido en el semestre en cuestión "),
            new Pregunta("Si el estudiante tiene más del 30% de avance en su carrera, con qué criterio lo evalúan para realizar traslado a otra sede?", "El PAPA debe estar entre los 30% más altos de la carrera en la sede a la que aplica"),
            new Pregunta("¿Cuándo se debe solicitar un examen supletorio?","5 días hábiles siguientes a la fecha de presentación de la evaluación ordinaria prevista"),
            new Pregunta("¿Cuantas sedes principales tiene la U nacional y cuantas de frontera?","5 sedes principales y 4 sedes frontera "),
            new Pregunta("¿Numero y nombre del edificio donde queda la rectoría de la Universidad?", "Edificio Uriel Gutiérrez - 861"),
            new Pregunta("¿Cuáles fueron 2 de las 4 profesiones adicionales a la de ingeniería que tuvo Julio Garavito Armero?","Astrónomo, matemático, economista y poeta."),
            new Pregunta("¿Nombre al menos una opción de pago de las multas de bibliotecas generadas por devolución tardía? ","Tres opciones: Pago virtual (//www.pagovirtual.unal.edu.co/), Pago en tesorería (Edificio Uriel Gutiérrez, tercer piso) y Pago en el banco popular (Cuenta bancaria)."),
            new Pregunta("¿Cuáles son los tres tipos de asignaturas que tiene un plan de estudios? ","Asignaturas de Fundamentación, Disciplinares y de libre elección."),
            new Pregunta("¿Mencione al menos una forma de demostrar la suficiencia de la lengua extranjera (Inglés) en la Universidad Nacional de Colombia?", "Opciones: 1. Superar el cuarto nivel de inglés en el examen de clasificación. 2. Superar el examen de suficiencia. 3. Aprobar los cuatros niveles de formación en la segunda lengua. 4. Presentar un certificado de suficiencia expedido por una institución de educación superior nacional o internacional."),
            new Pregunta("¿Qué día finaliza la cancelación de asignaturas con pérdida de créditos?  ","Octubre 25 del 2019"),
            new Pregunta("¿Cuál es el Acuerdo donde se encuentra el Estatuto Estudiantil de la Universidad Nacional de Colombia para disposiciones Académicas?", "Acuerdo 008 del 2008"),
            new Pregunta("¿Cuál es la oficina que se encarga de gestionar la movilidad académica y científica de estudiantes con Universidades Nacionales y Extranjeras?", "La Dirección de Relaciones Exteriores DRE"),
            new Pregunta("¿A dónde dirigirse para obtener más información sobre los apoyos socioeconómicos?", "Unidad Camilo Torres, bloque B-7"),
            new Pregunta("¿Como se llama el fundador del instituto de genética?", "Emilio Yunis"),
            new Pregunta("En caso de apelar una decisión del consejo de facultad ¿a qué entidad debo recurrir?", "Consejo superior universitario "),
            new Pregunta("¿Cuantas veces se puede tener la calidad de Admitido a pregrado en la UN?","4"),
            new Pregunta("¿Cuáles son las sanciones de tiempo cada vez que un estudiante pierde la calidad de estudiante?", "Primera vez: 1 semestre. Segunda vez: 5 semestres. Tercera vez: 10 semestres"),
            new Pregunta("¿Cuál es el mayor puntaje de PBM y hasta que puntaje no se pagan derechos de matrícula? ","100 y 11"),
            new Pregunta("¿Cuál es el acuerdo que reglamenta la doble titulación en convenio con otras universidades?.", "Acuerdo CSU 027 de 2010"),
            new Pregunta("¿A dónde acudir para pedir doble titulación?.", "Consejo de sede"),
            new Pregunta("¿Quién realiza el estudio de equivalencias y convalidaciones entre el primer y segundo plan de estudios?", "Comité asesor del segundo plan de estudios."),
            new Pregunta("Mencione una causal de pérdida de apoyo socioeconómico", "No cumplir con las horas de corresponsabilidad "),
            new Pregunta("Si tiene apoyo alimenticio y pasan dos semanas y no hace uso del apoyo (Sin notificación), lo pierde? ","Sí"),
            new Pregunta("Si le faltan 2 créditos para inscribir trabajo de grado, el consejo superior universitario le aprueba esos dos créditos que le hacen falta? ","No "),
    };
    public static Pregunta currentPregunta;
}
